[package]
name = "achess-ws"
version = "0.1.0"
authors = ["uros-5"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
bitintr = "0.3"
